### ISSUE TITLE
Improve training performance

### ISSUE THREAD

**Issue by slinlee** [PathmindAI/pathmind-webapp#1253]
The goal is to roughly match the speed of training on Ed's computer, while keeping the policy at the same performance.

### Using the Coffee Shop model, stats are:
**Current training time on webapp/aws:** 52 hours for 250 iterations. Maybe 31 hrs for 150 iterations
**Current training on Ed's laptop:** 15 hours for 150 iterations.

### Ideas:

- [x] Reduce number of workers to 8 #1215 
- [x] Decrease max_time_in_sec to 12 hours #1215 
- [x] increase CPU cores to 16 #1192 
- [x] Allow training to use all resources available #1254 
- [x] Implement early stopping #750 
- [ ] let users download policies from checkpoints
