### ISSUE TITLE
Deploy tuples to dev

### ISSUE THREAD

**Issue by ejunprung** [PathmindAI/pathmind-webapp#1653]
The only change is the action space (array of integers). I don't think the webapp looks at the action space so the changes should be pretty quick.

- [x] Remove multi-agent, single policy in test environment. It doesn't work with tuples and nobody has been successful with it. More simple to just maintain one thing instead of two.  https://github.com/SkymindIO/pathmind-webapp/issues/1654 @xneyder 
- [x] Upgrade AWS to 36 CPU instances. https://github.com/SkymindIO/pathmind-webapp/issues/1655 @ejunprung 
- [x] Test stop/resume with Ray 0.8.5. https://github.com/SkymindIO/nativerl/issues/63 @ejunprung 
- [ ] Update docs to reflect new Pathmind Helper layout. https://github.com/SkymindIO/pathmind-webapp/issues/1656@davisryanb @ejunprung 
- [ ] Set tuples length as an environment variable in webapp. Need to extract tuples length from model analyzer (just like how we do that for actions) https://github.com/SkymindIO/pathmind-webapp/issues/1666 @slinlee @kepricon 

I think that's it. The rest should be handled in NativeRL.
