### ISSUE TITLE
Policy Server UI parts

### ISSUE THREAD

**Issue by slinlee** [PathmindAI/pathmind-webapp#1665]
- [ ] Get inputs from user about observables, actions, etc. see what can be auto-generated since we'll be running the simulation (we can get examples of real observation inputs) This is a form in the UI that saves to the DB. https://github.com/SkymindIO/pathmind-webapp/issues/1664
- [ ] generate the YML file inputs for the policy server. https://github.com/SkymindIO/pathmind-webapp/issues/1690
- [ ] UI for creating an endpoint from the experiment page. This will connect to the next item about spinning up an instance with the proper inputs etc. #1691
- [ ] Spin up instances with the required inputs and routing. Including basic auth. #1669 

Future or nice to have?
- [ ] show a webform that the user can test the endpoint to see outputs.
- [ ] Monitoring for usage 
- [ ] improve auth security
