### ISSUE TITLE
Refactor BDD tests

### ISSUE THREAD

**Issue by slinlee** [PathmindAI/pathmind-webapp#1686]
### Tasks for this ticket:

- [x] speed up tests One feature file should contain 10 tests max. This should speed up tests
- [x] Move tests to the correct feature files. Order tests by elements on the page in the feature files.
- [x] Move methods to separate classes. Projects/Project/Model/Experiment/NewExperimen - create separate classes for these pages. Current ProjectPage class too big.
- [x] Create separate classes for common elements - Breadcrumbs, page header etc.

### Future tasks
- [ ] Create a list of the tags by pages. Add tags for each test.
- [ ] reduce waitABit calls in the project
- [ ] Review current tests coverage, create pending tests for new tests which will be implemented in the future
