### ISSUE TITLE
Show tooltips on the simulation metrics sparklines

### ISSUE THREAD

**Issue by slinlee** [PathmindAI/pathmind-webapp#1953]
#### TODOs
- [x] set up sparkline tooltip element, and callbacks in Polymer file (#1961)
- [x] set up sparkline tooltip styles in Polymer file (#1961)
- [ ] update sparkline Java file to accept iteration and episode
- [ ] pass in iteration and episode count into from sparkline Java file to sparkline Polymer file

Show a tooltip similar to the one used in the reward score chart. 

- Iteration
- value of simulation metric
- number of episodes <- this will help let users know how many samples are included in the mean.

![image](https://user-images.githubusercontent.com/1197406/89437619-a8c7f200-d6fc-11ea-9528-3e1e316be84b.png)
