### ISSUE TITLE
Update Pricing Page

### ISSUE THREAD

**Issue by fionnachan** [PathmindAI/pathmind-webapp#2689]
This ticket is part of #2651 

![image](https://user-images.githubusercontent.com/13184582/104276754-7955b680-54e0-11eb-9ce3-7bb4f318b9bc.png)

#### TODOs
- [ ] update pricing page content
- [ ] update pricing page styles
- [ ] make pricing page responsive
