### ISSUE TITLE
Comments on checklist content

### ISSUE THREAD

**Issue by slinlee** [PathmindAI/pathmind-webapp#848]
WIP

- [ ] Include instructions for exporting the model
- [ ] Actually ask the user to do something and give them the purpose for what they're doing.

- [ ] Add instructions to test validate the actions by running with random actions
- [ ] Trigger and actions should be first

- [ ] Use simple examples for the code. The coffeeshop one includes weird conditions that are added in the action function like, `if(server.status == idle)` that's just confusing and not the main point of that example.

- [ ] The instructions for reward variables just seem wrong.
